### ISSUE TITLE
Weird "fi" character spacing with Space Mono font

### ISSUE THREAD

**Issue by bengott** [thespacedojo/crater-nova#6]
Dunno why they did it this way, but anytime there's a word containing "fi", the "f" and the "i" are jammed together to fit into the width of one character, which makes it look ugly and a little hard to read. Seems strange that a monospaced font would do something like this? Not sure what the solution to this is, other than using a different font (I know you guys like Space Mono, though).

![weird-font-spacing](https://cloud.githubusercontent.com/assets/5376785/18839658/61b29f32-83d1-11e6-97f4-3a863626d8fd.png)

**Comment by bengott** [comment]
And here it is on Crater:
![weird-font-spacing-on-crater](https://cloud.githubusercontent.com/assets/5376785/18839844/0e1b7780-83d2-11e6-8ec9-b9c4845c6820.png)

**Comment by queso** [comment]
I'm not 100% tied to Space Mono, just felt fun. I think the idea of any
mono font would be fine and would fit with the theme at the end of the
day...

**Comment by bengott** [comment]
Fee "fi" fo fum, I smell weird font character spacing. ;)

**Comment by bengott** [comment]
Perhaps Roboto Mono would be a good alternative?
https://fonts.google.com/specimen/Roboto+Mono

**Comment by bengott** [comment]
I also opened an issue on the font's repo:
https://github.com/googlefonts/spacemono/issues/3

**Comment by SachaG** [comment]
I agree having a ligature in a monspaced font is weird. There might be a way to disable it using CSS though. See https://developer.mozilla.org/en/docs/Web/CSS/font-feature-settings

**Comment by bengott** [comment]
@SachaG So that what it's called when two characters are tied together like that? Learn somethin' every day. ;) The history of typography is pretty interesting. I could see burning 2 hours easy going down this Wikipedia rabbit hole...
https://en.wikipedia.org/wiki/Typographic_ligature

**Comment by SachaG** [comment]
```
font-feature-settings: "liga" 0;
```

That should work

**Comment by bengott** [comment]
Cool, thanks @SachaG. I updated my PR to disable ligatures and keep Space Mono, although I opted to use `font-variant-ligatures: no-common-ligatures;` just to be super explicit about it. Also, MDN recommends it over `font-feature-settings`.
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures

Cheers!

**Comment by Gregordy** [comment]
Applying some letter spacing also fixes the "fi" ligature.

```css
  letter-spacing: -0.0012rem;
```
